function openNav() {
    document.getElementById("mySidenav").style.width = "100%";
  }
  
  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
  }

  $(document).ready(function() {

    var arrLang={
        
        'tr':{
  
            '0':'Hakkımızda',
            '1':'Yaşamımızı iyileştirmek için iletişim profesyonellerinden oluşan bir ekibiz her günümüzü yükselten akıllı sürdürülebilir tasarımlı çevre deneyim, hem müşterilerimizin hem de kullanıcılarımızın ihtiyaçlarına hitap ediyor. Dising bu burada kalacak.',
            '2':'Metodolojimiz',
            '3':'Hedefler ve zorluklar',
            '4':'Müşterşlerinizin hedeflerini ve karşılaştıkları zorlukları belirleyerek, müşterileriniz için en uygun çözümleri sunmaya odaklanan bir stratejik planlama yöntemi olan Goals and Challenges metodolojisini aşşağıdaki adımlar takip ederek uyguluyoruz:',
            '5':'1. Müşterilerinizle bir araya gelerek işletmeleri hakkında bilgi topluyoruz.',
            '6':'2. Müşterilerinizin hedeflerini ve mevcut zorlukları belirliyoruz.',
            '7':'3. Rakiplerini, sektör trendlerini ve hedef kitlelerini araştırarak müşterileriniz ve işletmeleri için en uygun çözlümleri belirliyoruz.',
            '8':'4. Belirlediğiniz çözümleri, müşterinize sunun ve onların geri bildirimlerini alarak gerekli düzenlemeleri yapıyoruz.',
            '9':'Bu metodoloji, müşteriniz için özelleştirilmiş bir çözüm sunmanız ve müşteri memnunniyeti artırmanıza yardımcı olabilir.',
            '10':'Anlık ortam',
            '11':'Markanızın doğrudan etkileşimde bulunduğu çevreyi ve bu çevrenin işletmenin performansını nasıl etkilediğini analiz etmeye odaklanan bir stratejik planlama yaklaşımıdır. Bu metodolojiyi uygulamak için aşşağıdaki adımları takip edebilirsiniz:',
            '12':'1. İşletmenizin bulunduğu bölgenin sosyo-ekonomikk durumunu ve işletmenizin doğrudan etkileşiminde bulunduğu işletmeleri belirleyin.',
            '13':'2. Müşterinizin davranışlarını ve ihtiyaçlarını anlamak için pazar araştırması yapın İşletmenizdeki çalışanların, tedarikçilerin ve diğer iş ortaklarının işletmeniz üzerindeki etkilerini belirleyin.',
            '14':'3. Rekabet ortamını ve rakiplerinizi analiz edin.',
            '15':'Bu metodolojiyi, işletmenizde doğrudan etkileimde bulunduğu çevreyi anlayarak işletin.',
            '16':'Sosyo-Kültürel bağlam',
            '17':'İşletmenizin faaliyet gösterdiği toplumun tültürel, sosyal ve demografik özelliklerini anlamakta ve bu faktörlerin işletmeye nasıl etki ettiğini analiz etmek için kullanılan bir stratejik planlama yaklaşımıdır. bu metodolojiyi uygulamak için aşşağıdaki adımları takip edebilirsiniz:',
            '18':'1. İşletmenizin hizmet verdiği bölgenin kültürel ve demografik özelliklerini belirleyin.',
            '19':'2. Toplumun genel davranış ve alışkanlıklarını anlamak için pazar araştırması yapın.',
            '20':'3. Toplumun sosyal ve tültürel normlarını, inançlarını ve değerlerini analiz edin',
            '21':'4. Toplumun siyasi, ekonomik ve teknolojik orrtamını değerlendirin.',
            '22':'5. İşletmenizi bu sosyo -kültürel faktörlere nasıl uyum sağlayabileceğini belirleyin.',
            '23':'Bu metodoloji, işletmenizin faaliyet gösterdiği tolumun kültürel ve sosyal özellikleirni anlayarak müşterilerininzin ihtiyaçlarını daha iyi anlamaya yardımcı olabilir. Ayrıca işletmenizin bu faktörlere nasıl uyum sağlayabilecğini belirlemek, müşteri memnuniyetini artırmaya ve işletmenizin performansını iyileştirmeye yardımcı olabilir.',
            '24':'Verdiğimiz Hizmet',
            '25':'Marka stratejisi',
            '26':'Marka konumlandırma',
            '27':'Marka Adlandırma',
            '28':'Marka Değerleri / Misyon / Vizyon',
            '29':'Marka stratejisi',
            '30':'Marka Tasarımı',
            '31':'Kurumsal kimlik',
            '32':'Ambalaj ve Endüstriyel Tasarım',
            '33':'Web Tasarım, UX/UI',
            '34':'Web Geliştirme',
            '35':'Marka İletişimi',
            '36':'İletişim stratejisi',
            '37':'Metin yazarlığı',
            '38':'İçerik üretimi',
            '39':'Editoryal tasarım',
            '40':'Müşteriler',
            '41':'Ofis',
            '42':'Marka',
            '43':'Gizlilik Politikası',
            '44':'Dil',
            '45':'İngilizce',
            '46':'Almanca',
            '47':'Türkçe',
            '48':'Communication Design Ideas (CDI), İstanbul / Berlin merkezli, çok disiplinli, bağımsız bir tasarım stüdyosudur.',
            '49':'Disiplinler arası çalışma sistemimiz ve bağımsız kuruculardan köklü markalara uzanan müşteri portföyümüz ile markaların deneyimlerini oluşturan tüm etkileşim alanlarına hizmet veriyoruz.',
            '50':'İşler',
            '51':'Bizimle çalış',
            '52':'İletişim',
            '53':'Yeni iş:',
            '54':'Hakkımızda',
            '55':'İşler',
            '56':'İletişim',
            '57':'',
            '58':'',
            '59':'',
            '60':'',
            
        },
  
  
        'en':{
            '0':'About us',
            '1':'We are team of communication professionals to improve our living  envirionment with smart sustinable desing, that elevates our everyday experience, speaking to the needs of our clients and users alike. Dising that is here to stay.',
            '2':'Our Methodology',
            '3':'Goals and challenges',
            '4':'By identifying your customers goals and challenges, We apply the Goals and Challenges methodology, which is a strategic planning method focused on providing the most suitable solutions for your customers, by following the steps below:',
            '5':'1. We collect information about business meet-ups with your customers.',
            '6':'2. We identify your customers goals and current challenges.',
            '7':'3. We determine the most suitable solutions for your customers and businesses by researching their competitors, industry trends and target audiences.',
            '8':'4. Present the solutions you have determined to your customers and we take their feedback and make the necessary arrangements.',
            '9':'This methodology can help you provide a customized solution for your client and increase client satisfaction.',
            '10':'Instant environment',
            '11':'It is a strategic planning approach that focuses on analyzing the environment in which your brand interacts directly and how this environment affects the performance of the business. You can follow the steps below to apply this methodology:',
            '12':'1. Identify the socio-economic status of the region where your business is located and the businesses with which your business interacts directly.',
            '13':'2. Conduct market research to understand your customers behavior and needs Identify the effects of your employees, suppliers, and other business partners on your business.',
            '14':'3. Analyze the competitive landscape and your competitors.',
            '15':'Operate this methodology by understanding the environment in your business with which it directly interacts.',
            '16':'Socio - cultural context',
            '17':'It is a strategic planning approach used to understand the cultural, social and demographic characteristics of the society in which your business operates and to analyze how these factors affect the business. You can follow the steps below to apply this methodology:',
            '18':'1. Determine the cultural and demographic characteristics of the region your business serves.',
            '19':'2. Conduct market research to understand the general behavior and habits of the society.',
            '20':'3. Analyze the social and cultural norms, beliefs and values of the society',
            '21':'4. Evaluate the political, economic and technological environment of society.',
            '22':'5. Determine how your business can adapt to these socio-cultural factors.',
            '23':'This methodology can help you better understand your customers needs by understanding the cultural and social aspects of the community in which your business operates. Also, determining how your business can adapt to these factors can help increase customer satisfaction and improve your businesss performance.',
            '24':'Service We Provide',
            '25':'Brand Strategy',
            '26':'Brand positioning',
            '27':'Brand Naming',
            '28':'Brand Values / Mission /Vision',
            '29':'Brand Strategy',
            '30':'Brand Desing',
            '31':'Corporate Identity',
            '32':'Packaging and Industrial Desing',
            '33':'Web Desing, UX/UI',
            '34':'Web development',
            '35':'Brand Communication',
            '36':'Communication Strategy',
            '37':'Copywriting',
            '38':'Content production',
            '39':'Editorial design',
            '40':'Clients',
            '41':'Office',
            '42':'Imprint',
            '43':'Privacy Policy',
            '44':'Language',
            '45':'English',
            '46':'Deutch',
            '47':'Turkish',
            '48':'Communication Design Ideas (CDI) is a multi-disciplnary, independently owned design studio based in Istanbul / Berlin.',
            '49':'With our interdisciplinary work system and a customer portfolio from independent founders to established brands, we provide services to all interaction areas that make up the experiences of brands.',
            '50':'Works',
            '51':'Work with us',
            '52':'Contact',
            '53':'New Business:',
            '54':'Abount',
            '55':'Work',
            '56':'Contact',
            '57':'',
            '58':'',
            '59':'',
            '60':'',
          
        },
        'de':{
          
          '0':'Über uns',
          '1':'Wir sind ein Team von Kommunikationsprofis, um unser Lebensumfeld mit intelligentem, nachhaltigem Design zu verbessern, das unseren Alltag bereichert Erfahrung, die auf die Bedürfnisse unserer Kunden und Benutzer gleichermaßen eingeht. Dising ist hier, um zu bleiben.',
            '2':'Unsere Methodik',
            '3':'Ziele und Herausforderungen',
            '4':'Indem Sie die Ziele und Herausforderungen Ihrer Kunden identifizieren Wir wenden die Goals and Challenges-Methodik an, eine strategische Planungsmethode, die sich darauf konzentriert, die am besten geeigneten Lösungen für Ihre Kunden bereitzustellen, indem wir die folgenden Schritte ausführen:',
            '5':'1. Wir treffen uns mit Ihren Kunden, um Informationen über ihre Geschäfte zu sammeln.',
            '6':'2. Wir identifizieren die Ziele und aktuellen Herausforderungen Ihrer Kunden.',
            '7':'3. Wir ermitteln die am besten geeigneten Lösungen für Ihre Kunden und Unternehmen, indem wir ihre Wettbewerber, Branchentrends und Zielgruppen recherchieren.',
            '8':'4. Präsentieren Sie Ihren Kunden die von Ihnen ermittelten Lösungen, und wir nehmen ihr Feedback auf und treffen die erforderlichen Vorkehrungen.',
            '9':'Diese Methodik kann Ihnen helfen, eine maßgeschneiderte Lösung für Ihren Kunden bereitzustellen und die Kundenzufriedenheit zu steigern.',
            '10':'Sofortige Umgebung',
            '11':'Es ist ein strategischer Planungsansatz, der sich darauf konzentriert, das Umfeld zu analysieren, in dem Ihre Marke direkt interagiert, und wie sich dieses Umfeld auf die Leistung des Unternehmens auswirkt. Sie können die folgenden Schritte ausführen, um diese Methode anzuwenden:',
            '12':'1. Identifizieren Sie den sozioökonomischen Status der Region, in der sich Ihr Unternehmen befindet, und die Unternehmen, mit denen Ihr Unternehmen direkt interagiert.',
            '13':'2. Führen Sie Marktforschung durch, um das Verhalten und die Bedürfnisse Ihrer Kunden zu verstehen. Identifizieren Sie die Auswirkungen Ihrer Mitarbeiter, Lieferanten und anderen Geschäftspartner auf Ihr Unternehmen.',
            '14':'3. Analysieren Sie die Wettbewerbslandschaft und Ihre Konkurrenten.',
            '15':'Wenden Sie diese Methodik an, indem Sie die Umgebung in Ihrem Unternehmen verstehen, mit der sie direkt interagiert.',
            '16':'Soziokultureller Kontext',
            '17':'Es ist ein strategischer Planungsansatz, der verwendet wird, um die kulturellen, sozialen und demografischen Merkmale der Gesellschaft, in der Ihr Unternehmen tätig ist, zu verstehen und zu analysieren, wie diese Faktoren das Unternehmen beeinflussen. Sie können die folgenden Schritte ausführen, um diese Methode anzuwenden:',
            '18':'1. Bestimmen Sie die kulturellen und demografischen Merkmale der Region, in der Ihr Unternehmen tätig ist.',
            '19':'2. Führen Sie Marktforschung durch, um das allgemeine Verhalten und die Gewohnheiten der Gesellschaft zu verstehen.',
            '20':'3. Analysieren Sie die sozialen und kulturellen Normen, Überzeugungen und Werte der Gesellschaft',
            '21':'4. Bewerten Sie das politische, wirtschaftliche und technologische Umfeld der Gesellschaft.',
            '22':'5. Bestimmen Sie, wie sich Ihr Unternehmen an diese soziokulturellen Faktoren anpassen kann.',
            '23':'Diese Methodik kann Ihnen helfen, die Bedürfnisse Ihrer Kunden besser zu verstehen, indem Sie die kulturellen und sozialen Aspekte der Gemeinschaft verstehen, in der Ihr Unternehmen tätig ist. Auch die Bestimmung, wie sich Ihr Unternehmen an diese Faktoren anpassen kann, kann dazu beitragen, die Kundenzufriedenheit zu erhöhen und die Leistung Ihres Unternehmens zu verbessern.',
            '24':'Dienstleistungen, die wir anbieten',
            '25':'Markenstrategie',
            '26':'Markenpositionierung',
            '27':'Markenname',
            '28':'Markenwerte / Mission / Vision',
            '29':'Markenstrategie',
            '30':'Markendesign',
            '31':'Unternehmensidentität',
            '32':'Verpackung und Industriedesign',
            '33':'Webdesign, UX/UI',
            '34':'Web Entwicklung',
            '35':'Markenkommunikation',
            '36':'Kommunikationsstrategie',
            '37':'Werbetexten',
            '38':'Produktion von Inhalten',
            '39':'Redaktionellen Gestaltung',
            '40':'Kunden',
            '41':'Büro',
            '42':'Impressum',
            '43':'Datenschutz-Bestimmungen',
            '44':'Sprache',
            '45':'Englisch',
            '46':'Deutsch',
            '47':'Türkisch',
            '48':'Communication Design Ideas (CDI) ist ein multidisziplinäres, unabhängiges Designstudio mit Sitz in Istanbul / Berlin.',
            '49':'Mit unserem interdisziplinären Arbeitssystem und einem Kundenportfolio von unabhängigen Gründern bis hin zu etablierten Marken erbringen wir Dienstleistungen für alle Interaktionsbereiche, die Markenerlebnisse ausmachen.',
            '50':'Funktioniert',
            '51':'Arbeite mit uns',
            '52':'Kontakt',
            '53':'Neues Geschäft:',
            '54':'Über',
            '55':'Funktioniert',
            '56':'Kontakt',
            '57':'',
            '58':'',
            '59':'',
            '60':'',
        
      },
        
        
    };
  
  
    
  $('.language').click(function() {
    localStorage.setItem('dil', JSON.stringify($(this).attr('id'))); 
    location.reload();
  });
  
    var lang =JSON.parse(localStorage.getItem('dil'));
  
   
  
    $('a,h5,p,h1,h2,span,li,button,h3,label').each(function(index,element) {
      $(this).text(arrLang[lang][$(this).attr('key')]);
    
  });
  
  });
   